import 'package:celus_fe/core/api/api_consumer.dart';
import 'package:celus_fe/core/api/end_ponits.dart';
import 'package:celus_fe/core/models/send_otp_model.dart';
import 'package:celus_fe/helper/error/failures.dart';
import 'package:dartz/dartz.dart';

class SendOtpVm {
  final ApiConsumer apiConsumer;
  SendOtpVm({required this.apiConsumer});
  Future<Either<Failure, Autogenerated>> postOtp({
    required String phoneNumber,
  }) async {
    try {
      final response = await apiConsumer.post(
        EndPoint.sendOtp,queryParameters: {'phone':phoneNumber},
      );
      Autogenerated autogenerated = Autogenerated.fromJson(response);

      print(autogenerated);
      return Right(autogenerated);
    } on Exception catch (e) {
      return Left(ServerFailure.handleException(e));
    }
  }
  Future<Either<Failure, Autogenerated>> verifyOtp({
    required String otp,
  }) async {
  //   try {
  //     final response = await apiConsumer.post(
  //       EndPoint.sendOtp,queryParameters: {'phone':phoneNumber},
  //     );
  //     Autogenerated autogenerated = Autogenerated.fromJson(response);

  //     print(autogenerated);
  //     return Right(autogenerated);
  //   } on Exception catch (e) {
  //     return Left(ServerFailure.handleException(e));
  //   }
  return Right(Autogenerated());
  }
}
