class Autogenerated {
  Data? data;
  String? errors;
  String? timestamp;

  Autogenerated({this.data, this.errors, this.timestamp});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    data = json['data'] != null ? new Data.fromJson(json['data']) : null;
    errors = json['errors'];
    timestamp = json['timestamp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    data['errors'] = this.errors;
    data['timestamp'] = this.timestamp;
    return data;
  }
}

class Data {
  Null? name;
  bool? existing;

  Data({this.name, this.existing});

  Data.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    existing = json['existing'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['existing'] = this.existing;
    return data;
  }
}